
version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=history
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    image: piacentini08/api-rest-challenge:latest
    depends_on:
      - db
      - external-service
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/history
      - third.party.http.client.url=http://external-service:8081
    ports:
      - '8080:8080'
    links:
      - db
      - external-service
  external-service:
    image: piacentini08/external-service:latest
    ports:
      - '8081:8081'


volumes:
  db:
    driver: local

